// <auto-generated />
using System;
using BookSoft.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookSoft.Infrastructure.Migrations
{
    [DbContext(typeof(BookSoftDbContext))]
    [Migration("20260512103415_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppointmentPractitioner", b =>
                {
                    b.Property<Guid>("AppointmentsID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PractitionersID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AppointmentsID", "PractitionersID");

                    b.HasIndex("PractitionersID");

                    b.ToTable("AppointmentPractitioner");
                });

            modelBuilder.Entity("BookSoft.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PatientID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("PatientID");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("BookSoft.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Birthday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("BookSoft.Domain.Entities.Practitioner", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Practitioners");
                });

            modelBuilder.Entity("AppointmentPractitioner", b =>
                {
                    b.HasOne("BookSoft.Domain.Entities.Appointment", null)
                        .WithMany()
                        .HasForeignKey("AppointmentsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookSoft.Domain.Entities.Practitioner", null)
                        .WithMany()
                        .HasForeignKey("PractitionersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookSoft.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("BookSoft.Domain.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientID");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("BookSoft.Domain.Entities.Patient", b =>
                {
                    b.OwnsOne("BookSoft.Domain.ValueObjects.FullName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("PatientID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MiddleNames")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PatientID");

                            b1.ToTable("Patients");

                            b1.WithOwner()
                                .HasForeignKey("PatientID");
                        });

                    b.Navigation("FullName")
                        .IsRequired();
                });

            modelBuilder.Entity("BookSoft.Domain.Entities.Practitioner", b =>
                {
                    b.OwnsOne("BookSoft.Domain.ValueObjects.FullName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("PractitionerID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MiddleNames")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PractitionerID");

                            b1.ToTable("Practitioners");

                            b1.WithOwner()
                                .HasForeignKey("PractitionerID");
                        });

                    b.Navigation("FullName")
                        .IsRequired();
                });

            modelBuilder.Entity("BookSoft.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
